#' Data used to train the model.
#'
#' A dataset containing five X variables and other auxiliary variables
#'
#' @format A data frame with 2000 rows and 10 variables:
#' \describe{
#'   \item{X1}{binary, 0 or 1}
#'   \item{X2}{binary, 0 or 1}
#'   \item{X3}{binary, 0 or 1}
#'   \item{X4}{binary, 0 or 1}
#'   \item{X5}{binary, 0 or 1}
#'   \item{Y}{dependent variable, continuous}
#'   \item{IV}{instrumental variable, continuous}
#'   ...
#' }
#' @source The data is generated by data_generator.R in data-raw directory 
"data_all"



#' Data used to test the performance of tree model.
#'
#' A dataset containing five X variables and other auxiliary variables
#'
#' @format A data frame with 5000 rows and 10 variables:
#' \describe{
#'   \item{X1}{binary, 0 or 1}
#'   \item{X2}{binary, 0 or 1}
#'   \item{X3}{binary, 0 or 1}
#'   \item{X4}{binary, 0 or 1}
#'   \item{X5}{binary, 0 or 1}
#'   \item{Y}{dependent variable, continuous}
#'   \item{IV}{instrumental variable, continuous}
#'   ...
#' }
#' @source The data is generated by data_generator.R in data-raw directory 
"data_te"